# Generated by Django 5.1.3 on 2025-01-08 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('png', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='reg',
            name='email',
            field=models.EmailField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='reg',
            name='password',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='reg',
            name='youtube_URL',
            field=models.URLField(null=True),
        ),
    ]
