# Generated by Django 5.1.3 on 2025-01-08 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('png', '0002_reg_email_reg_password_reg_youtube_url'),
    ]

    operations = [
        migrations.CreateModel(
            name='event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('event_img', models.ImageField(upload_to='', verbose_name='event_img/')),
                ('event_date', models.DateField(auto_now_add=True)),
                ('details', models.TextField(max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='news',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('image', models.ImageField(upload_to='news_img/')),
                ('date', models.DateField(auto_now_add=True)),
                ('details', models.TextField(max_length=250)),
            ],
        ),
        migrations.AlterField(
            model_name='reg',
            name='password',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
