# Generated by Django 5.1.3 on 2025-01-08 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('png', '0004_alter_news_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='event_date',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='news',
            name='date',
            field=models.DateField(null=True),
        ),
    ]
