# Generated by Django 5.1.3 on 2025-01-08 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('png', '0005_alter_event_event_date_alter_news_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='event_date',
            field=models.DateField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='event',
            name='event_img',
            field=models.ImageField(upload_to='', verbose_name='event_img'),
        ),
        migrations.AlterField(
            model_name='news',
            name='date',
            field=models.DateField(auto_now_add=True, null=True),
        ),
    ]
