# Generated by Django 5.1.3 on 2025-01-10 08:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('png', '0011_alter_news_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='reg',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=10),
        ),
    ]
